# 这里是整个后端的service，暴露端口
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app-service
    app: axum-ddd-start 
spec:
  type: NodePort # 这里是NodePort类型，这样就可以通过NodeIP:NodePort来访问服务
  ports:
  - port: 8080 # 服务端口
    targetPort: 8080 # Pod端口
    nodePort: 30004 # NodePort端口
  selector: # 选择要暴露的Pod
    name: app-pod
    app: axum-ddd-start