apiVersion: v1
kind: Service
metadata:
  name: postgres # 服务名称，写代码连接用这个名称
  labels:
    name: postgres-service
    app: axum-ddd-start
spec:
  ports:
  - port: 5432 # 服务端口
    targetPort: 5432 # Pod端口
  selector: # 选择要暴露的Pod
    name: postgres-pod
    app: axum-ddd-start