apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: axum-ddd-start
spec:
  containers:
    - name: postgres
      image: postgres:latest
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: "root123456"
      resources: # 限制资源
        limits:
          memory: "128Mi"
          cpu: "500m"