apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: axum-ddd-start
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
      resources: # 限制资源
        limits:
          memory: "128Mi"
          cpu: "500m"